export const nation = [
  // Africa
  { name: "Algerian", region: "North Africa", country: "Algeria", flag: "🇩🇿" },
  { name: "Angolan", region: "Central Africa", country: "Angola", flag: "🇦🇴" },
  { name: "Beninese", region: "West Africa", country: "Benin", flag: "🇧🇯" },
  { name: "Botswanan", region: "Southern Africa", country: "Botswana", flag: "🇧🇼" },
  { name: "Burkinabé", region: "West Africa", country: "Burkina Faso", flag: "🇧🇫" },
  { name: "Burundian", region: "East Africa", country: "Burundi", flag: "🇧🇮" },
  { name: "Cameroonian", region: "Central Africa", country: "Cameroon", flag: "🇨🇲" },
  { name: "Cape Verdean", region: "West Africa", country: "Cape Verde", flag: "🇨🇻" },
  { name: "Central African", region: "Central Africa", country: "Central African Republic", flag: "🇨🇫" },
  { name: "Chadian", region: "Central Africa", country: "Chad", flag: "🇹🇩" },
  { name: "Comorian", region: "East Africa", country: "Comoros", flag: "🇰🇲" },
  { name: "Congolese (DRC)", region: "Central Africa", country: "DR Congo", flag: "🇨🇩" },
  { name: "Congolese", region: "Central Africa", country: "Republic of Congo", flag: "🇨🇬" },
  { name: "Djiboutian", region: "East Africa", country: "Djibouti", flag: "🇩🇯" },
  { name: "Egyptian", region: "North Africa", country: "Egypt", flag: "🇪🇬" },
  { name: "Equatorial Guinean", region: "Central Africa", country: "Equatorial Guinea", flag: "🇬🇶" },
  { name: "Eritrean", region: "East Africa", country: "Eritrea", flag: "🇪🇷" },
  { name: "Eswatini", region: "Southern Africa", country: "Eswatini", flag: "🇸🇿" },
  { name: "Ethiopian", region: "East Africa", country: "Ethiopia", flag: "🇪🇹" },
  { name: "Gabonese", region: "Central Africa", country: "Gabon", flag: "🇬🇦" },
  { name: "Gambian", region: "West Africa", country: "Gambia", flag: "🇬🇲" },
  { name: "Ghanaian", region: "West Africa", country: "Ghana", flag: "🇬🇭" },
  { name: "Guinean", region: "West Africa", country: "Guinea", flag: "🇬🇳" },
  { name: "Bissau-Guinean", region: "West Africa", country: "Guinea-Bissau", flag: "🇬🇼" },
  { name: "Ivorian", region: "West Africa", country: "Côte d'Ivoire", flag: "🇨🇮" },
  { name: "Kenyan", region: "East Africa", country: "Kenya", flag: "🇰🇪" },
  { name: "Basotho", region: "Southern Africa", country: "Lesotho", flag: "🇱🇸" },
  { name: "Liberian", region: "West Africa", country: "Liberia", flag: "🇱🇷" },
  { name: "Libyan", region: "North Africa", country: "Libya", flag: "🇱🇾" },
  { name: "Malagasy", region: "East Africa", country: "Madagascar", flag: "🇲🇬" },
  { name: "Malawian", region: "East Africa", country: "Malawi", flag: "🇲🇼" },
  { name: "Malian", region: "West Africa", country: "Mali", flag: "🇲🇱" },
  { name: "Mauritanian", region: "West Africa", country: "Mauritania", flag: "🇲🇷" },
  { name: "Mauritian", region: "East Africa", country: "Mauritius", flag: "🇲🇺" },
  { name: "Moroccan", region: "North Africa", country: "Morocco", flag: "🇲🇦" },
  { name: "Mozambican", region: "East Africa", country: "Mozambique", flag: "🇲🇿" },
  { name: "Namibian", region: "Southern Africa", country: "Namibia", flag: "🇳🇦" },
  { name: "Nigerien", region: "West Africa", country: "Niger", flag: "🇳🇪" },
  { name: "Nigerian", region: "West Africa", country: "Nigeria", flag: "🇳🇬" },
  { name: "Rwandan", region: "East Africa", country: "Rwanda", flag: "🇷🇼" },
  { name: "São Toméan", region: "Central Africa", country: "São Tomé and Príncipe", flag: "🇸🇹" },
  { name: "Senegalese", region: "West Africa", country: "Senegal", flag: "🇸🇳" },
  { name: "Seychellois", region: "East Africa", country: "Seychelles", flag: "🇸🇨" },
  { name: "Sierra Leonean", region: "West Africa", country: "Sierra Leone", flag: "🇸🇱" },
  { name: "Somali", region: "East Africa", country: "Somalia", flag: "🇸🇴" },
  { name: "South African", region: "Southern Africa", country: "South Africa", flag: "🇿🇦" },
  { name: "South Sudanese", region: "East Africa", country: "South Sudan", flag: "🇸🇸" },
  { name: "Sudanese", region: "North Africa", country: "Sudan", flag: "🇸🇩" },
  { name: "Tanzanian", region: "East Africa", country: "Tanzania", flag: "🇹🇿" },
  { name: "Togolese", region: "West Africa", country: "Togo", flag: "🇹🇬" },
  { name: "Tunisian", region: "North Africa", country: "Tunisia", flag: "🇹🇳" },
  { name: "Ugandan", region: "East Africa", country: "Uganda", flag: "🇺🇬" },
  { name: "Zambian", region: "Southern Africa", country: "Zambia", flag: "🇿🇲" },
  { name: "Zimbabwean", region: "Southern Africa", country: "Zimbabwe", flag: "🇿🇼" },

  // Asia
  { name: "Afghan", region: "Central Asia", country: "Afghanistan", flag: "🇦🇫" },
  { name: "Bangladeshi", region: "South Asia", country: "Bangladesh", flag: "🇧🇩" },
  { name: "Bhutanese", region: "South Asia", country: "Bhutan", flag: "🇧🇹" },
  { name: "Bruneian", region: "Southeast Asia", country: "Brunei", flag: "🇧🇳" },
  { name: "Cambodian", region: "Southeast Asia", country: "Cambodia", flag: "🇰🇭" },
  { name: "Chinese", region: "East Asia", country: "China", flag: "🇨🇳" },
  { name: "Filipino", region: "Southeast Asia", country: "Philippines", flag: "🇵🇭" },
  { name: "Indian", region: "South Asia", country: "India", flag: "🇮🇳" },
  { name: "Indonesian", region: "Southeast Asia", country: "Indonesia", flag: "🇮🇩" },
  { name: "Japanese", region: "East Asia", country: "Japan", flag: "🇯🇵" },
  { name: "Kazakh", region: "Central Asia", country: "Kazakhstan", flag: "🇰🇿" },
  { name: "Korean", region: "East Asia", country: "South Korea", flag: "🇰🇷" },
  { name: "Kyrgyz", region: "Central Asia", country: "Kyrgyzstan", flag: "🇰🇬" },
  { name: "Laotian", region: "Southeast Asia", country: "Laos", flag: "🇱🇦" },
  { name: "Malaysian", region: "Southeast Asia", country: "Malaysia", flag: "🇲🇾" },
  { name: "Maldivian", region: "South Asia", country: "Maldives", flag: "🇲🇻" },
  { name: "Mongolian", region: "East Asia", country: "Mongolia", flag: "🇲🇳" },
  { name: "Burmese", region: "Southeast Asia", country: "Myanmar", flag: "🇲🇲" },
  { name: "Nepalese", region: "South Asia", country: "Nepal", flag: "🇳🇵" },
  { name: "North Korean", region: "East Asia", country: "North Korea", flag: "🇰🇵" },
  { name: "Pakistani", region: "South Asia", country: "Pakistan", flag: "🇵🇰" },
  { name: "Singaporean", region: "Southeast Asia", country: "Singapore", flag: "🇸🇬" },
  { name: "Sri Lankan", region: "South Asia", country: "Sri Lanka", flag: "🇱🇰" },
  { name: "Tajik", region: "Central Asia", country: "Tajikistan", flag: "🇹🇯" },
  { name: "Thai", region: "Southeast Asia", country: "Thailand", flag: "🇹🇭" },
  { name: "Timorese", region: "Southeast Asia", country: "Timor-Leste", flag: "🇹🇱" },
  { name: "Turkmen", region: "Central Asia", country: "Turkmenistan", flag: "🇹🇲" },
  { name: "Uzbek", region: "Central Asia", country: "Uzbekistan", flag: "🇺🇿" },
  { name: "Vietnamese", region: "Southeast Asia", country: "Vietnam", flag: "🇻🇳" },

  // Middle East
  { name: "Bahraini", region: "Middle East", country: "Bahrain", flag: "🇧🇭" },
  { name: "Iranian", region: "Middle East", country: "Iran", flag: "🇮🇷" },
  { name: "Iraqi", region: "Middle East", country: "Iraq", flag: "🇮🇶" },
  { name: "Israeli", region: "Middle East", country: "Israel", flag: "🇮🇱" },
  { name: "Jordanian", region: "Middle East", country: "Jordan", flag: "🇯🇴" },
  { name: "Kuwaiti", region: "Middle East", country: "Kuwait", flag: "🇰🇼" },
  { name: "Lebanese", region: "Middle East", country: "Lebanon", flag: "🇱🇧" },
  { name: "Omani", region: "Middle East", country: "Oman", flag: "🇴🇲" },
  { name: "Palestinian", region: "Middle East", country: "Palestine", flag: "🇵🇸" },
  { name: "Qatari", region: "Middle East", country: "Qatar", flag: "🇶🇦" },
  { name: "Saudi", region: "Middle East", country: "Saudi Arabia", flag: "🇸🇦" },
  { name: "Syrian", region: "Middle East", country: "Syria", flag: "🇸🇾" },
  { name: "Emirati", region: "Middle East", country: "UAE", flag: "🇦🇪" },
  { name: "Yemeni", region: "Middle East", country: "Yemen", flag: "🇾🇪" },

  // Europe
  { name: "Albanian", region: "Europe", country: "Albania", flag: "🇦🇱" },
  { name: "Andorran", region: "Europe", country: "Andorra", flag: "🇦🇩" },
  { name: "Armenian", region: "Europe", country: "Armenia", flag: "🇦🇲" },
  { name: "Austrian", region: "Europe", country: "Austria", flag: "🇦🇹" },
  { name: "Azerbaijani", region: "Europe", country: "Azerbaijan", flag: "🇦🇿" },
  { name: "Belarusian", region: "Europe", country: "Belarus", flag: "🇧🇾" },
  { name: "Belgian", region: "Europe", country: "Belgium", flag: "🇧🇪" },
  { name: "Bosnian", region: "Europe", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { name: "Bulgarian", region: "Europe", country: "Bulgaria", flag: "🇧🇬" },
  { name: "Croatian", region: "Europe", country: "Croatia", flag: "🇭🇷" },
  { name: "Cypriot", region: "Europe", country: "Cyprus", flag: "🇨🇾" },
  { name: "Czech", region: "Europe", country: "Czech Republic", flag: "🇨🇿" },
  { name: "Danish", region: "Europe", country: "Denmark", flag: "🇩🇰" },
  { name: "Dutch", region: "Europe", country: "Netherlands", flag: "🇳🇱" },
  { name: "Estonian", region: "Europe", country: "Estonia", flag: "🇪🇪" },
  { name: "Finnish", region: "Europe", country: "Finland", flag: "🇫🇮" },
  { name: "French", region: "Europe", country: "France", flag: "🇫🇷" },
  { name: "Georgian", region: "Europe", country: "Georgia", flag: "🇬🇪" },
  { name: "German", region: "Europe", country: "Germany", flag: "🇩🇪" },
  { name: "Greek", region: "Europe", country: "Greece", flag: "🇬🇷" },
  { name: "Hungarian", region: "Europe", country: "Hungary", flag: "🇭🇺" },
  { name: "Icelandic", region: "Europe", country: "Iceland", flag: "🇮🇸" },
  { name: "Irish", region: "Europe", country: "Ireland", flag: "🇮🇪" },
  { name: "Italian", region: "Europe", country: "Italy", flag: "🇮🇹" },
  { name: "Kosovar", region: "Europe", country: "Kosovo", flag: "🇽🇰" },
  { name: "Latvian", region: "Europe", country: "Latvia", flag: "🇱🇻" },
  { name: "Lithuanian", region: "Europe", country: "Lithuania", flag: "🇱🇹" },
  { name: "Luxembourgish", region: "Europe", country: "Luxembourg", flag: "🇱🇺" },
  { name: "Maltese", region: "Europe", country: "Malta", flag: "🇲🇹" },
  { name: "Moldovan", region: "Europe", country: "Moldova", flag: "🇲🇩" },
  { name: "Montenegrin", region: "Europe", country: "Montenegro", flag: "🇲🇪" },
  { name: "North Macedonian", region: "Europe", country: "North Macedonia", flag: "🇲🇰" },
  { name: "Norwegian", region: "Europe", country: "Norway", flag: "🇳🇴" },
  { name: "Polish", region: "Europe", country: "Poland", flag: "🇵🇱" },
  { name: "Portuguese", region: "Europe", country: "Portugal", flag: "🇵🇹" },
  { name: "Romanian", region: "Europe", country: "Romania", flag: "🇷🇴" },
  { name: "Russian", region: "Europe", country: "Russia", flag: "🇷🇺" },
  { name: "Serbian", region: "Europe", country: "Serbia", flag: "🇷🇸" },
  { name: "Slovak", region: "Europe", country: "Slovakia", flag: "🇸🇰" },
  { name: "Slovenian", region: "Europe", country: "Slovenia", flag: "🇸🇮" },
  { name: "Spanish", region: "Europe", country: "Spain", flag: "🇪🇸" },
  { name: "Swedish", region: "Europe", country: "Sweden", flag: "🇸🇪" },
  { name: "Swiss", region: "Europe", country: "Switzerland", flag: "🇨🇭" },
  { name: "Turkish", region: "Europe", country: "Turkey", flag: "🇹🇷" },
  { name: "Ukrainian", region: "Europe", country: "Ukraine", flag: "🇺🇦" },
  { name: "British", region: "Europe", country: "United Kingdom", flag: "🇬🇧" },

  // North America
  { name: "American", region: "North America", country: "United States", flag: "🇺🇸" },
  { name: "Canadian", region: "North America", country: "Canada", flag: "🇨🇦" },
  { name: "Mexican", region: "North America", country: "Mexico", flag: "🇲🇽" },
  { name: "Cuban", region: "Caribbean", country: "Cuba", flag: "🇨🇺" },
  { name: "Dominican", region: "Caribbean", country: "Dominican Republic", flag: "🇩🇴" },
  { name: "Haitian", region: "Caribbean", country: "Haiti", flag: "🇭🇹" },
  { name: "Jamaican", region: "Caribbean", country: "Jamaica", flag: "🇯🇲" },
  { name: "Costa Rican", region: "Central America", country: "Costa Rica", flag: "🇨🇷" },
  { name: "Guatemalan", region: "Central America", country: "Guatemala", flag: "🇬🇹" },
  { name: "Honduran", region: "Central America", country: "Honduras", flag: "🇭🇳" },
  { name: "Panamanian", region: "Central America", country: "Panama", flag: "🇵🇦" },
  { name: "Salvadoran", region: "Central America", country: "El Salvador", flag: "🇸🇻" },
  { name: "Trinidadian", region: "Caribbean", country: "Trinidad and Tobago", flag: "🇹🇹" },

  // South America
  { name: "Argentine", region: "South America", country: "Argentina", flag: "🇦🇷" },
  { name: "Bolivian", region: "South America", country: "Bolivia", flag: "🇧🇴" },
  { name: "Brazilian", region: "South America", country: "Brazil", flag: "🇧🇷" },
  { name: "Chilean", region: "South America", country: "Chile", flag: "🇨🇱" },
  { name: "Colombian", region: "South America", country: "Colombia", flag: "🇨🇴" },
  { name: "Ecuadorian", region: "South America", country: "Ecuador", flag: "🇪🇨" },
  { name: "Paraguayan", region: "South America", country: "Paraguay", flag: "🇵🇾" },
  { name: "Peruvian", region: "South America", country: "Peru", flag: "🇵🇪" },
  { name: "Uruguayan", region: "South America", country: "Uruguay", flag: "🇺🇾" },
  { name: "Venezuelan", region: "South America", country: "Venezuela", flag: "🇻🇪" },

  // Oceania
  { name: "Australian", region: "Oceania", country: "Australia", flag: "🇦🇺" },
  { name: "Fijian", region: "Oceania", country: "Fiji", flag: "🇫🇯" },
  { name: "New Zealander", region: "Oceania", country: "New Zealand", flag: "🇳🇿" },
  { name: "Papua New Guinean", region: "Oceania", country: "Papua New Guinea", flag: "🇵🇬" },
];